application: gopokedex
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: api/.*
  script: api_handler.app
- url: input/.*
  script: input_handler.app
- url: .*
  script: main_handler.app
